# Generated by Django 6.0.8 on 2026-09-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='1-based position inside the track')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('xp_reward', models.PositiveIntegerField(default=50, help_text='Bonus XP for clearing the level')),
            ],
            options={
                'ordering': ('track__order', 'index'),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='*', max_length=8)),
                ('accent', models.CharField(default='#7c5cff', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required_xp', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(help_text='Markdown')),
                ('minutes', models.PositiveIntegerField(default=5)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.level')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('mcq', 'Multiple choice'), ('multi', 'Multiple answers'), ('short', 'Short answer'), ('code', 'Code')], max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('prompt', models.TextField(help_text='Markdown')),
                ('hint', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True, help_text='Shown after a correct answer')),
                ('xp', models.PositiveIntegerField(default=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('solution', models.JSONField(blank=True, default=dict)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='curriculum.level')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='level',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='curriculum.track'),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('track', 'index')},
        ),
    ]
